[package]
name = "template-rust-project"
version = "0.0.0"
edition = "2024"
rust-version = "1.98.0"
license = "CC-BY-ND-4.0"
publish = false

[lints.rust]
future_incompatible = { level = "deny", priority = -1 }
let_underscore = { level = "deny", priority = -1 }
missing_docs = "deny"
non_ascii_idents = "deny"
rust_2018_idioms = { level = "deny", priority = -1 }
unreachable_pub = "deny"
warnings = { level = "deny", priority = -1 }
unsafe_code = "forbid"

[lints.clippy]
all = { level = "deny", priority = -1 }
cargo = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
